slurm:
    wall_time: "1000:00:00"
    atoms_per_processor: 6
    max_processors: 20
    ram_per_processor: 2

mongoDB:
    host: "jules.schleinitz"
    port: 27017
    user: "julosdu13"
    password: "yPbcgFmN6Uji9Gt"
