#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C10H10N2_b1cc_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C10H10N2_b1cc_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C10H15BO2_9b2b_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C10H15BO2_9b2b_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C10H16Li2OZn_e65a_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C10H16Li2OZn_e65a_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C10H16N2O2_4a56_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C10H16N2O2_4a56_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C10H18O3SSi_03d1_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C10H18O3SSi_03d1_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C10H20B2O4_e307_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C10H20B2O4_e307_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C10H7BrMg_1cfc_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C10H7BrMg_1cfc_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C10H7BrMg_3b16_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C10H7BrMg_3b16_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C10H7NO3_6183_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C10H7NO3_6183_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C10H9BO2_4281_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C10H9BO2_4281_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C11H10O_b7a8_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C11H10O_b7a8_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C11H12N2_0c5e_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C11H12N2_0c5e_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C11H14BFO2_09a4_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C11H14BFO2_09a4_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C11H15BO2_e653_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C11H15BO2_e653_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C11H15N_9ae3_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C11H15N_9ae3_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C11H16N2O2_bc12_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C11H16N2O2_bc12_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C11H19Li2NZn_9b52_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C11H19Li2NZn_9b52_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C11H9F3N2_5379_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C11H9F3N2_5379_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C11H9N3_3fa8_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C11H9N3_3fa8_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C12H14BF3O2_4f2d_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C12H14BF3O2_4f2d_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C12H15BO4_a84c_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C12H15BO4_a84c_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C12H17BO2_ad28_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C12H17BO2_ad28_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C12H19FO3Si_a02e_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C12H19FO3Si_a02e_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C12H20O3Si_7f04_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C12H20O3Si_7f04_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C12H24B2O5_0a3d_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C12H24B2O5_0a3d_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C12H25Al_0a70_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C12H25Al_0a70_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C12H27BO2Si_5b6c_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C12H27BO2Si_5b6c_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C12H27BO3Si_cb43_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C12H27BO3Si_cb43_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C12H27P_7353_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C12H27P_7353_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C13H16Li2Zn_45f7_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C13H16Li2Zn_45f7_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C13H17BO3_7e4d_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C13H17BO3_7e4d_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C13H17BO4_7f3d_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C13H17BO4_7f3d_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C13H17N3O_20e7_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C13H17N3O_20e7_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C13H19BO2_00d0_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C13H19BO2_00d0_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C13H19F3O3Si_549c_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C13H19F3O3Si_549c_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C13H20BNO2_a1a2_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C13H20BNO2_a1a2_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C13H20Li2O2Zn_0b90_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C13H20Li2O2Zn_0b90_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C13H22O3Si_9808_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C13H22O3Si_9808_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C13H22O3Si_b8f7_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C13H22O3Si_b8f7_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C13H22O3Si_fa60_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C13H22O3Si_fa60_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C13H22O4Si_58ca_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C13H22O4Si_58ca_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C13H22O4Si_7792_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C13H22O4Si_7792_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C13H22O4Si_fc94_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C13H22O4Si_fc94_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C14H12N2_1ac7_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C14H12N2_1ac7_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C14H14N2_8636_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C14H14N2_8636_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C14H18BNO2_25f8_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C14H18BNO2_25f8_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C14H22O5Si_a0fd_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C14H22O5Si_a0fd_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C14H23Al_25ee_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C14H23Al_25ee_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C14H23BO2Si_30da_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C14H23BO2Si_30da_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C14H23BO2Si_434f_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C14H23BO2Si_434f_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C14H24O3Si_02e1_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C14H24O3Si_02e1_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C14H24O3Si_c57b_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C14H24O3Si_c57b_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C14H9BrMg_6c9f_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C14H9BrMg_6c9f_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C15H17BO2_0ca9_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C15H17BO2_0ca9_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C15H17BO2_a2c3_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C15H17BO2_a2c3_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C15H18Li2Zn_c5a2_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C15H18Li2Zn_c5a2_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C15H22AlF3_037b_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C15H22AlF3_037b_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C15H23BO2_a3b3_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C15H23BO2_a3b3_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C15H25Al_eb83_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C15H25Al_eb83_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C15H25AlO_6cc2_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C15H25AlO_6cc2_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C16H14N2_fb3d_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C16H14N2_fb3d_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C16H22O3Si_435d_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C16H22O3Si_435d_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C16H27Al_6d81_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C16H27Al_6d81_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C16H27Li2NOZn_c371_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C16H27Li2NOZn_c371_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C16H28O3Si_7635_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C16H28O3Si_7635_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C16H30Li2OSiZn_953c_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C16H30Li2OSiZn_953c_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C17H19BO2_fa16_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C17H19BO2_fa16_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C17H21NO3_90d6_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C17H21NO3_90d6_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C17H32Li2OSiZn_cf69_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C17H32Li2OSiZn_cf69_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C18H14BrMgN_f7eb_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C18H14BrMgN_f7eb_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C18H15Al_12b3_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C18H15Al_12b3_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C18H15P_e364_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C18H15P_e364_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C18H19NO2_5d34_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C18H19NO2_5d34_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C19H39AlSi_687a_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C19H39AlSi_687a_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C20H28O2_1cb0_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C20H28O2_1cb0_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C20H28O2_1cb0_conf_1.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C20H28O2_1cb0_conf_1#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C21H12F9P_775b_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C21H12F9P_775b_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C21H21B3O3_21ad_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C21H21B3O3_21ad_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C21H21B3O6_f970_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C21H21B3O6_f970_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C21H21P_396c_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C21H21P_396c_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C21H21P_a83d_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C21H21P_a83d_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C23H34N2_ed6f_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C23H34N2_ed6f_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C24H20BK_ed49_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C24H20BK_ed49_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C24H27B3O3_2e14_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C24H27B3O3_2e14_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C24H27B3O9_ad56_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C24H27B3O9_ad56_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C28H28P2_2ea3_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C28H28P2_2ea3_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C29H37N2P_2034_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C29H37N2P_2034_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C29H42N2_7304_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C29H42N2_7304_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C30H39B3O3_7d3a_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C30H39B3O3_7d3a_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C30H56P2_49fd_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C30H56P2_49fd_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C33H49P_45b2_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C33H49P_45b2_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C34H36N3P_0c83_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C34H36N3P_0c83_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C36H28B6O6_2802_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C36H28B6O6_2802_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C37H52OP2_3e33_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C37H52OP2_3e33_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C39H32OP2_1fb1_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C39H32OP2_1fb1_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C39H56OP2_3ca6_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C39H56OP2_3ca6_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C3H5N3_b3b4_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C3H5N3_b3b4_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C40H32N3P_cc14_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C40H32N3P_cc14_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C40H44N3P_fdbf_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C40H44N3P_fdbf_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C44H32P2_d184_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C44H32P2_d184_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C45H27B3O9_afc5_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C45H27B3O9_afc5_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C45H53N2P_f523_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C45H53N2P_f523_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C45H71N2P_889c_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C45H71N2P_889c_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C46H67P_8b90_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C46H67P_8b90_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C46H67P_a2c6_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C46H67P_a2c6_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C4H14OSi2_fa5f_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C4H14OSi2_fa5f_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C4H3BF3KN2_d9e0_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C4H3BF3KN2_d9e0_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C4H3BF3KS_83b3_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C4H3BF3KS_83b3_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C4H3BF3KS_cb21_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C4H3BF3KS_cb21_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C4H5BO3_0dd5_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C4H5BO3_0dd5_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C4H5BO3_a701_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C4H5BO3_a701_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C4H9BrMg_1287_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C4H9BrMg_1287_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C5H4BF3KN_2eb6_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C5H4BF3KN_2eb6_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C5H4BF3KN_e22e_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C5H4BF3KN_e22e_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C6H5BF3K_f96e_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C6H5BF3K_f96e_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C6H5ClZn_9380_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C6H5ClZn_9380_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C6H6BFO2_ce66_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C6H6BFO2_ce66_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C7H10N2O2_d878_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C7H10N2O2_d878_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C7H6BF3O2_8acb_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C7H6BF3O2_8acb_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C7H7BrMn_80d0_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C7H7BrMn_80d0_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C7H7ClOZn_e5d7_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C7H7ClOZn_e5d7_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C7H7ClZn_5370_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C7H7ClZn_5370_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C8H11Al_67ae_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C8H11Al_67ae_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C8H11BO2_3a14_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C8H11BO2_3a14_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C8H11BO2_b26d_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C8H11BO2_b26d_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C8H12OSi_ea11_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C8H12OSi_ea11_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C8H7BO3_4119_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C8H7BO3_4119_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C8H9ClOZn_3aff_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C8H9ClOZn_3aff_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C9H10N2O_0efd_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C9H10N2O_0efd_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C9H11BrMg_e4d5_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C9H11BrMg_e4d5_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C9H13N3_f867_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C9H13N3_f867_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C9H14AlLi_61d4_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C9H14AlLi_61d4_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C9H14O3Si_a49a_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C9H14O3Si_a49a_conf_0#! /bin/bash
#SBATCH -J runG09
#SBATCH --ntasks=1
#SBATCH --time 1000:00:00
#SBATCH --output C9H7F3O_5a77_conf_0.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jules.schleinitz@ens.fr

#############################################################

module purge
module load gaussian

source ${g09root}/g09.profile

g09 C9H7F3O_5a77_conf_0